R/pstr_add_transition_risk.R
R/pstr_aggregate_scores.R
README.md
inst/extdata/mvp/product-sector-transition-risk.Rmd
man/pstr_add_transition_risk.Rd
man/pstr_aggregate_scores.Rd
tests/testthat/test-pstr_aggregate_scores.R

Also rename arguments to be more informative and consistent.

* Fix missing arugment `companies`

---

R/pstr_add_reductions.R
R/pstr_add_transition_risk.R
R/pstr_aggregate_scores.R
R/pstr_plot_company.R
man/pstr_add_reductions.Rd
man/pstr_add_transition_risk.Rd
man/pstr_aggregate_scores.Rd
man/pstr_plot_company.Rd

Closes #26.
I have added documentation for the `pstr_*`functions, namely : 
- pstr_add_reductions()
- pstr_add_transition_risk()
- pstr_aggregate_score()
- pstr_plot_company()
I have put a title, wrote a brief description, described the params and return, and wrote examples for each one of them.
Thank you ! :)

Document the `pstr_*()` functions

---

R/pctr_data.R
_pkgdown.yml
man/pctr_companies.Rd
man/pctr_ecoinvent_co2.Rd

- New family to document pctr datasets
- Document

New family to document pctr data

---

NEWS.md
R/pstr_add_reductions.R
R/pstr_add_transition_risk.R
R/pstr_aggregate_scores.R
R/pstr_data.R
R/pstr_plot_company.R
_pkgdown.yml
man/companies.Rd
man/ep_weo.Rd
man/pstr_add_reductions.Rd
man/pstr_add_transition_risk.Rd
man/pstr_aggregate_scores.Rd
man/pstr_plot_company.Rd
man/weo_2022.Rd

This PR adds a new `@family` to group related functions. This makes it easier for the user to discover related functions and to navigate between them. Also it make it easy to organize the related functions in the Reference section of the website.
@lindadelacombaz, while this touches files you own I'll bypass your review because it isn't worth your time. This is a safe change that doesn't touch production code.

New family to relate pstr functions

---

R/mvp_path.R
R/render_to_list.R
R/use_refactoring_checklist.R
_pkgdown.yml
inst/extdata/mvp/pctr.Rmd
man/mvp_path.Rd
man/render_to_list.Rd
man/use_refactoring_checklist.Rd

- In PCTR remove plots
- Make internal functions internal

Make internal functions internal

---

R/pstr_add_transition_risk.R
R/pstr_plot_company.R
man/pstr_add_transition_risk.Rd
man/pstr_plot_company.Rd

This PR prepares to defunc uprefixed pstr data.

Use prefixed data

---

README.Rmd
README.md
vignettes/articles/pstr.Rmd

Because our immediate deliverables are datasets, 
Tilman and I agreed to de-prioritize plots.
This PR doesn't remove the plotting code so it's backward compatible and safe. Thus I'll merge without review.

Remove plots

---

R/pctr_score_activities.R
man/pctr_score_activities.Rd

Set default thresholds

---

R/pctr_score_activities.R
R/pctr_score_companies.R

Closes #82 
Dear @maurolepore ,
Please let me know if have missed any important info or could exclude anything you find irrelevant! Thanks!

document pctr functions

---

R/pctr_score_activities.R
R/pctr_score_companies.R
man/pctr_score_activities.Rd
man/pctr_score_companies.Rd

@kalashsinghal sorry I guided you in the wrong way. I noticed the docs were incorrect so I moved the `@description` tag around and finally found the right position for it. You may see it in "Files changed".
Once the checks pass, I'll go ahead and merge since I already know what was the intent.

Fix the description of pctr functions

---

R/ictr_data.R
R/ictr_score_companies.R
R/ictr_score_inputs.R
R/pctr_data.R
R/pctr_score_activities.R
R/pctr_score_companies.R
R/pstr_add_reductions.R
R/pstr_add_transition_risk.R
R/pstr_aggregate_scores.R
R/pstr_data.R
R/utils.R
man/ictr_companies.Rd
man/ictr_inputs.Rd
man/ictr_score_companies.Rd
man/ictr_score_inputs.Rd
man/pctr_companies.Rd
man/pctr_ecoinvent_co2.Rd
man/pctr_score_activities.Rd
man/pctr_score_companies.Rd
man/pstr_add_reductions.Rd
man/pstr_add_transition_risk.Rd
man/pstr_aggregate_scores.Rd
man/pstr_companies.Rd
man/pstr_ep_weo.Rd
man/pstr_weo_2022.Rd

This PR documents the author of each dataset and function. Beyond the entry in the article and DESCRIPTION this is important because the authors didn't add the code themselves to git so the author in the git history is me instead. With this it should be clearer from the helpfile of each object who authored it.

Document authorship in place

---

vignettes/articles/ictr.Rmd

closes #120 
Dear @maurolepore 
Thanks for sharing how to do the custom search for searching keywords in specific files! I have made the required change after learning this new feature. Thanks! :)

Replace "pctr" with "ictr" in ictr files

---

R/ictr_data.R
R/ictr_score_companies.R
R/ictr_score_inputs.R
man/ictr_companies.Rd
man/ictr_inputs.Rd
man/ictr_score_companies.Rd
man/ictr_score_inputs.Rd
tests/testthat/test-istr.R
vignettes/articles/istr.Rmd

closes #93 
Please have a look on the documentation of ICTR functions. Thanks for the review!

Document ICTR functions

---

inst/extdata/child/intro-ictr.Rmd
inst/extdata/child/intro-istr.Rmd
inst/extdata/child/intro-pctr.Rmd
inst/extdata/child/intro-pstr.Rmd

closes #156 
Dear @maurolepore 
As requested by you, I have changed the text of the child files from future to present tense. I haven't added any new information in this PR about any indicator. Thanks for the review!

Changed info in child files from future to present tense 

---

inst/extdata/child/intro-ictr.Rmd
inst/extdata/child/intro-istr.Rmd
inst/extdata/child/intro-pctr.Rmd
inst/extdata/child/intro-pstr.Rmd
inst/extdata/mvp/istr.Rmd

- Remove references to 'MVP'
- Use the present tense

Polish get started

---

R/ictr_score_companies.R
R/pctr_score_companies.R
tests/testthat/test-ictr_score_companies.R
tests/testthat/test-pctr_score_companies.R

Join only by *uuid

---

R/istr.R
R/istr_add_reductions.R
R/istr_mapping.R
R/utils-istr.R
man/istr_add_reductions.Rd
man/istr_aggregate_scores.Rd
man/istr_mapping.Rd
tests/testthat/test-istr_add_reductions.R
tests/testthat/test-istr_aggregate_scores.R
tests/testthat/test-istr_mapping.R

In ISTR test common behaviour

---

R/istr.R
R/pstr.R
tests/testthat/test-ictr.R
tests/testthat/test-istr.R
tests/testthat/test-pctr.R
tests/testthat/test-pstr.R

- Ungroup pstr()
- Ungroup
- Test ungroup

Remove groupgs

---

R/ictr.R
R/pctr.R
R/utils-xctr.R
R/utils.R
R/xctr_at_company_level.R
man/ictr.Rd
man/istr.Rd
man/pctr.Rd
man/pstr.Rd
tests/testthat/test-ictr.R
tests/testthat/test-pctr.R

- wip
- refactor
- refactor
- refactor
- refactor
- refactor
- refactor
- refactor
- refactor
- refactor
- refactor
- refactor
- Refactor
- refactor
- refactor
- redocument

199 In xctr rename at product level

---

R/ictr.R
R/pctr.R
R/xctr.R
man/ictr.Rd
man/ictr_datasets.Rd
man/pctr.Rd
man/pctr_datasets.Rd
tests/testthat/test-ictr.R
tests/testthat/test-pctr.R

- tdd
- refactor
- refactor
- Relocate
- refactor

230 Handle duplicated co2

---

R/ictr.R
R/pctr.R
R/xctr.R
man/ictr.Rd
man/pctr.Rd

- Change more thresholds
- Redocument

Change more thresholds that I forgot before

---

R/utils-xctr.R
R/utils.R
tests/testthat/test-ictr_at_product_level.R
tests/testthat/test-pctr_at_product_level.R

246 prune needless columns

---

R/utils-xctr.R
tests/testthat/test-xctr_at_product_level.R

At product level XCTR now drops NA from unmatched products

---

vignettes/articles/handling-long-runtime.Rmd

Polish article

---

vignettes/articles/handling-long-runtime.Rmd

Relates to #283 
This PR improves the article about handling long run time. It biulds on my recent experience runing `pstr*()`.
----
TODO
EXCEPTIONS

Update article based on experience running `pstr*()`

---

tests/testthat/test-pstr.R
tests/testthat/test-xctr-inputs.R
tests/testthat/test-xctr.R

This is only refactoring to keep tests a bit more organized.
----
TODO
EXCEPTIONS

Refactor: Group similar tests

---

tests/testthat/_snaps/istr.md
tests/testthat/_snaps/istr_prepare_companies.md
tests/testthat/test-istr.R
tests/testthat/test-istr_prepare_companies.R
tests/testthat/test-pstr_at_product_level.R
tests/testthat/test-pstr_prepare_companies.R
tests/testthat/test-pstr_prepare_scenario.R

Dear @maurolepore 
This PR is the follow-up work after this [PR](https://github.com/2DegreesInvesting/tiltIndicator/pull/357) for this [issue](https://github.com/2DegreesInvesting/tiltIndicator/issues/354). I have included snapshot tests for ISTR with additional TODOs which can only be completed after I will update the `pstr_prepare` functions to `xstr_prepare` functions in another PR. 
I have not changed any logic of the code, and have just added snapshot tests and some TODOs. Therefore, I am merging this PR without any review. Please review it after your holidays! Thanks!
----
TODO
EXCEPTIONS

Add snapshot tests and TODOs for ISTR

---

R/data.R
_pkgdown.yml
man/companies.Rd

Closes #373 
This PR re-organizes the Reference section of the website. The XSTR functions are now well tested so they are no longer experimental.
----
TODO
EXCEPTIONS
This PR touches no production code. It only affects the looks of the website.

Polish website's Reference

---

inst/extdata/child/intro-ictr.Rmd
inst/extdata/child/intro-istr.Rmd
inst/extdata/child/intro-pctr.Rmd

Relates to #352 
In #352 I simplified cross-references but R CMD check warned missing links so this PR restores the full reference to the links.
----
TODO
EXCEPTIONS
This change affects only the website and is a hotfix.

Add missing links to avoid R CMD check warning

---

R/istr.R
R/pstr.R
R/utils.R
R/xctr.R
R/xctr_at_product_level.R

Closes #392 
This PR ensures all outputs have no duplicates. 
----
TODO
EXCEPTIONS
I think it's no longer possible to get duplicated outputs since #393 and since #399 -- hence I can not create a test that fails before I add the code in this PR. This means the code here is redundant, but I prefer to make sure. This way, if future outputs have duplicates I will know the problem is in downstream code (e.g. in the script I currently use to run the indicators).

* Ensure all outputs have no duplicate

---

inst/extdata/child/intro-ictr.Rmd

Relates to #463 
Requested by @Tilmon via https://2investinginitiative.slack.com/archives/D0372LLRA0Z/p1689780301036699
----
TODO
EXCEPTIONS
I seen an error building the website on GitHub actions but it's unrelated to the change -- the error happens even if I trigger the workflow without any change. To bypass this unrelated problem I'll build the site locally and push it via `pkgdown::build_site_github_pages()`.
```bash
Error in curl::curl_fetch_memory(url, handle = handle) : 
SSL peer certificate or SSH remote key was not OK: [www.bioconductor.org] SSL: no alternative certificate subject name matches target host name 'www.bioconductor.org'
Calls: <Anonymous> ... withVisible -> eval -> eval -> <Anonymous> -> <Anonymous>
Execution halted
Error: Process completed with exit code 1.
```

Update intro-ictr.Rmd to fulfull grant requirements

---

R/emissions_profile.R
R/emissions_profile_upstream.R
R/sector_profile.R
R/sector_profile_upstream.R
_pkgdown.yml
man/emissions_profile.Rd
man/emissions_profile_upstream.Rd
man/sector_profile.Rd
man/sector_profile_upstream.Rd
vignettes/articles/tiltIndicator.Rmd

Relates to #477 
Following the upgrade to new names (#477) the public API is now smaller and we no longer need so much structure to organize the Reference. This PR simplifies that organization.
----
TODO
EXCEPTIONS

Simplify the "Reference" section of the website

---

R/emissions_profile.R
R/sector_profile.R
R/sector_profile_upstream.R
R/utils.R
man/emissions_profile.Rd
man/emissions_profile_upstream.Rd
man/sector_profile.Rd
man/sector_profile_upstream.Rd
tests/testthat/_snaps/utils.md
tests/testthat/test-utils.R

Relates to #477 
Closes #500 
See description there.
----
TODO
EXCEPTIONS

Avoid broken links to deprecated datasets

---

vignettes/articles/extending-outputs.Rmd

This PR polishes the article that shows how to extend results at product level with columns from input datasets.
----
TODO
EXCEPTIONS

Polish the article to more clearly reflect its intent

---

R/emissions_profile_any_add_values_to_categorize.R
R/emissions_profile_any_at_product_level.R

Relates to #566
This PR renames an internal function. It's pure refectoring.
----
TODO
EXCEPTIONS

Rename to emissions_profile_any_add_values_to_categorize

---

vignettes/articles/handling-long-runtime.Rmd

This PR fixes a mistake.
----
TODO
EXCEPTIONS

Fix `job_map()`

---

tests/testthat/_snaps/emissions_profile.md
tests/testthat/_snaps/emissions_profile_upstream.md
tests/testthat/test-emissions_profile_upstream.R

Hotfix following 2DegreesInvesting/tiltToyData#19
Fix one test that failed with the latest change to tiltToyData.
----
TODO
EXCEPTIONS

Fix a test to reflect new toy data

---

data/deprecated.R
man/deprecated.Rd

Complements #667 
This PR replaces more instances of `*products()` to `*products_ecoinvent()`
----
TODO
EXCEPTIONS

Replace more instances of `*products()` with `*products_ecoinvent()`

---

DESCRIPTION
inst/extdata/child/intro-emissions_profile.Rmd
man/emissions_profile.Rd

Closes #681
----
TODO
EXCEPTIONS

Add Tilman's edits on the helpfile of `emissions_profile()`

---

.github/workflows/install-from-r-universe.yaml

Closes #680
----
TODO
EXCEPTIONS

Install from r-universe on CI

---

README.Rmd
README.md

Closes #678
----
TODO
EXCEPTIONS

The installation instructions now include r-universe

---

README.Rmd
README.md

Update README to better reflect the goal of the tiltIndicator package

---

.github/workflows/R-CMD-check.yaml

Closes #679 
----
TODO
EXCEPTIONS

Update CI workflows to check with R versions back to oldrel-2

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION

Closes #677
Depend on R 4.1.0 (2021-05-18)
----
TODO
EXCEPTIONS

Depend on R 4.1.0 (released on 2021-05-18)

---

.github/workflows/install-from-r-universe.yaml
README.Rmd
README.md

Install from r-universe with pak::repo_add()

---

README.Rmd
README.md

Update installation instructions

---

README.Rmd
README.md

The goal is to provide r-universe as a version of the installation process that requires the minimum elements.
----
TODO
EXCEPTIONS

Remove pak from r-universe installation

---

man/deprecated.Rd
tests/testthat/_snaps/emissions_profile.md
tests/testthat/_snaps/emissions_profile_upstream.md

Dear @maurolepore This PR updates the snapshots in tiltIndicator package after toy datasets of emissions profile are changed using this [PR](https://github.com/2DegreesInvesting/tiltToyData/pull/38).
----
TODO
EXCEPTIONS

Update snapshots after change in emissions profile toy datasets

---

tests/testthat/_snaps/emissions_profile.md
tests/testthat/_snaps/emissions_profile_upstream.md

@maurolepore This PR updates the snapshots after change in column `companies_id` in file `toy_emissions_profile_any_companies`. Reference: https://github.com/2DegreesInvesting/tiltToyData/pull/40
----
TODO
EXCEPTIONS

Update snapshots for change in `companies_id`

---

man/deprecated.Rd

Update `deprecated.Rd` file after updating toy datasets.

---

tests/testthat/_snaps/emissions_profile_upstream.md

Relates to https://github.com/2DegreesInvesting/tiltToyData/pull/45
This PR updates snapshot after resolving issue [#17](https://github.com/2DegreesInvesting/tiltToyDataPrivate/issues/17) in tiltToyDataPrivate
----
TODO
EXCEPTIONS

Update snapshot after resolving issue #17 in tiltToyDataPrivate

---

DESCRIPTION
LICENSE.md

Closes #673
----
TODO
EXCEPTIONS

Use license GPLv3

---

R/emissions_profile.R
R/emissions_profile_any_at_product_level.R
R/epa_at_company_level.R
tests/testthat/_snaps/emissions_profile.md
tests/testthat/test-emissions_profile.R
tests/testthat/test-emissions_profile_any_at_company_level.R
tests/testthat/test-emissions_profile_upstream.R

- Preserve unmatched products and missing benchmarks
- WIP at company level
----
TODO
EXCEPTIONS

Implement 638 at company level

---

R/standalone-name-pattern.R
tests/testthat/test-standalone-name-pattern.R

Closes #762
----
TODO
EXCEPTIONS

`check_matches_name()` now handles multiple matches

---

R/emissions_profile.R
R/profile.R
R/sector_profile.R
R/sector_profile_upstream.R
tests/testthat/test-emissions_profile.R
tests/testthat/test-emissions_profile_upstream.R
tests/testthat/test-profile.R
tests/testthat/test-sector_profile.R
tests/testthat/test-sector_profile_upstream.R

This PR creates the class 'profile' and provides a the `profiile()` constructor. This also includes `is_profile()`, an a developer facing validator and constructor.
Advice from https://adv-r.hadley.nz/s3.html#s3-classes
The goal is to allow polymorphic behaviour downstrem.
----
TODO
EXCEPTIONS

New class 'profile', and friends `profile()`, `is_profile()`

---

.github/workflows/call-R-CMD-check-tiltWebTool.yaml
.github/workflows/call-R-CMD-check.yaml

Call reusable workflows

---

R/standalone-check_crucial_names.R
R/utils.R

This allows reusing `check_crucial_names()` more easily and in a principled way.
----
TODO

New standalone-check_crucial_names

---

DESCRIPTION

* Relates to https://github.com/2DegreesInvesting/TiltDevProjectMGMT/issues/215
----
TODO

Make Kalash the maintainer
