2DegreesInvesting/tiltIndicator

R/pstr_add_reductions.R, R/pstr_add_transition_risk.R, R/pstr_aggregate_scores.R, man/pstr_add_reductions.Rd, man/pstr_add_transition_risk.Rd, man/pstr_aggregate_scores.Rd
When documenting `f()` avoid writing "`f()` ..." because it's
redundant and is one more thing we need to update when we rename
f() to something else.
=> Polish docs for style and maintainability

R/ictr_score_companies.R, R/pctr_score_companies.R, tests/testthat/test-ictr_score_companies.R, tests/testthat/test-pctr_score_companies.R
Closes #111 
Dear @maurolepore ,
After having a deeper look why this [test](https://github.com/2DegreesInvesting/tiltIndicator/blob/main/tests/testthat/test-ictr_score_companies.R#:~:text=test_that(%22the,%7D)) is failing through the debugger, I found an argument to be arbitrary. 
Hence, I have resolved the bug through this PR and changed the test related to this bug as well. In my further commits, I will resolve the bug also present in `pctr_score_companies` function. Thanks for your upcoming comments!
=> Fix `ictr_score_companies()` and  `pctr_score_companies()`

DESCRIPTION, NEWS.md
This PR marks that the bug in `*pctr_score_companies()` is fixed. In NEWS I explicitly articulate my new understanding: These functions are expected to return exactly three rows for each company.
This PR is low risk as it touches no code. I'll merge without review and check with @kalashsinghal via a follow up PR, where I  formalize that in helpfiles and tests (#113).
=> Bump version and update NEWS.md

tests/testthat/test-pctr_score_companies.R
This PR adds tests to characterize odd behavoiur of `pctr_score_companies()`. Before I did it informally in the article pctr-questions.Rmd.
This tests are in preparation to debug the function -- so I know when I fix it.
FYI @kalashsinghal you may find tests here useful as both `*ctr_score_companies()` functions share so much code they likely share bugs.
=> Characterize odd edge cases of `pstr_score_companies()`

DESCRIPTION, NEWS.md, R/pctr_score_companies.R, tests/testthat/test-pctr_score_companies.R, vignettes/articles/pctr-questions.Rmd
Closes #122 
This PR replaces `inner_join()` with `left_join()` to preserve all companies.
See `?dplyr::inner_join()`:
> An inner_join() only keeps observations from x that have a matching key in y.
> The most important property of an inner join is that unmatched rows in either input are not included in the result. This means that generally inner joins are not appropriate in most analyses, because it is too easy to lose observations.
=> * FIX: pctr_score_companies()` no longer drops companies depending on the number of rows of co2 data

tests/testthat/test-pstr.R
Closes #133.
Here is my take on testing pstr() similar to pctr() and istr().
- I added two tests on verifying crucial columns on companies and scenarios (named `companies` and `inputs` in pctr / istr)
- I saw that pctr() and istr() tested if there were a missing value on the `reductions` column (called inputs$inputs_co2 in ictr). `pstr()` does not throw an error if the `reductions` column in the pstr_scenario data set is NA. This would be a great question for @Tilmon to know if this should throw an error or not.
- I wrote again the test for the edge cases. I wrote a "#TODO" to create a toy data set that work for this cases, since there is a lot of left_joining going on :). 
Let me know if I missed something ! 
Thanks !
=> Test `pstr()` similar to `pctr()` and `istr()`

R/ictr.R, R/pctr.R, R/xctr.R, tests/testthat/_snaps/ictr.md, tests/testthat/_snaps/pctr.md
@maurolepore 
This PR removes duplication in ICTR & PCTR through `xctr_add_scores` function. This PR partially completes #201. I will try to remove the for loop tomorrow. Thanks!
=> Remove duplication through `xctr_add_scores` function in ICTR & PCTR

DESCRIPTION, NEWS.md, R/ictr.R, R/pctr.R, R/utils-xctr.R, R/xctr.R, tests/testthat/test-ictr.R, tests/testthat/test-pctr.R
Closes #230
@Tilmon, removing the `clustered` column leaves the `companies` dataset with duplicated rows. That's likely the cause of the error you get. Removing the duplicates works with no error (for a tiny sample of `copmanies`). 
To avoid this from happening again, ICTR and PCTR now remove duplicates internally. The reprex below shows how to fix the problem by removing the duplicates, or by using the latest version of the package (after this PR).
``` r
library(dplyr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)
options(readr.show_col_types = FALSE)
here <- function(...) fs::path("~/Downloads/", ...)
nrows <- 3L
companies_raw <- read_csv(here("input_data/ctr_companies.csv"), n_max = nrows)
anyDuplicated(companies_raw)
#> [1] 0
companies <- companies_raw |> …
```
=> ICTR and PCTR now handle duplicated `companies`

R/utils-xctr.R, R/utils.R, tests/testthat/test-ictr.R, tests/testthat/test-ictr_at_product_level.R, tests/testthat/test-istr.R, tests/testthat/test-pctr.R, tests/testthat/test-pctr_at_product_level.R, tests/testthat/test-pstr.R
Relates to #199 
New output columns:
* `clustered`
* `activity_uuid_product_uuid`
* `input_activity_uuid_product_uuid`
Despite slight differences in column names, this meets the minimum requirements in the [googlesheet template](https://docs.google.com/spreadsheets/d/1K1thTMRg-k4DSdJy-G1RFY0islOQk70ToU3zmCKmvHM/edit#gid=1913268156).
The exception are ISTR and PSTR at product level because the example datasets (and code) lack some of the required columns.
=> `xctr_at_product_level()` now outputs `clustered` and `*_uuid`

.github/pull_request_template.md
This PR adds a PR template with a checklist to remember, among other thigns, to change the PR status from draft to ready.
It doesn't touch production code so I can't add a unit test for it. I'll test it by opening a toy PR after merging.
=> New PR template with a checklist of important things to do

DESCRIPTION, vignettes/articles/handling-long-runtime.Rmd
Closes #185 
This article shows how to calculate an indicator when it takes too long to run. It shows an approach that shows your progress, avoids running the same thing twice, and allows you to restart from where you left if something fails or you need to interrupt.
----
TODO
EXCEPTIONS
No because this PR doesn't touch code and I'm flying solo.
=> New article handling long runtime

R/istr.R, R/pstr.R, R/utils-xstr.R, tests/testthat/test-istr.R, tests/testthat/test-pstr.R, vignettes/articles/handling-long-runtime.Rmd
Closes #296 
For consistency with XCTR, missing values in `reductions` now yield an error. This also simplifies the code since we don't need to write code to handle those missing values.
----
TODO
EXCEPTIONS
=> In `xstr*()`, `NA`s in `reductions` now trigger an error

R/pstr.R, tests/testthat/test-pstr.R, tests/testthat/test-pstr_at_product_level.R
Closes #199 
This PR makes `pstr*()` return columns as close as possible as in the googlesheet template.
@Tilmon 
Beyond those columns I also output the column `type` which describes e.g. "ipr" versis "weo". This column is not part of `grouped_by` and likely the cause of the bug described here #302.
Once I merge this PR please check the output of `pstr_at_product_level()` in the [helpfile](https://2degreesinvesting.github.io/tiltIndicator/reference/pstr.html#ref-examples) and confirm you're OK with it. This will count as your after-the-fact review.
----
TODO
EXCEPTIONS
=> `pstr_at_product_level()` now output columns as in the google sheet template

R/utils-xstr.R, tests/testthat/_snaps/pstr.md, tests/testthat/test-pstr.R
Closes #302 
This PR adds the type of scenario to the column `grouped_by`. This more closely reflects the googlesheet template.
----
TODO
EXCEPTIONS
=> The column `grouped_by` now includes the scenario type

R/istr.R, R/pstr.R, R/utils-xstr.R, tests/testthat/test-pstr.R
Closes #310 
Follow up #308 
This PR introduces an assertion that would help users avoid the problem in #309. It errors if the `scenarios` dataset has a `type` where all rows of `sector` and `subsector` are `NA`. 
``` r
library(dplyr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)
options(readr.show_col_types = FALSE)
library(tiltIndicator)
packageVersion("tiltIndicator")
#> [1] '0.0.0.9055'
companies <- pstr_companies
old_scenarios <- list(
ipr = read_csv(extdata_path("pstr_ipr_2022.csv")),
weo = read_csv(extdata_path("pstr_weo_2022.csv"))
) |>
pstr_prepare_scenario()
pstr(companies, old_scenarios) |> 
filter(is.na(value))
#> # A tibble: 42 × 4
#>    companies_id                             grouped_by risk_category value
#>    <chr> …
```
=> Each scenario `type` must have some `sector` and `subsector`

R/istr.R, R/pstr.R, R/utils-xstr.R, tests/testthat/test-pstr.R
This PR adds a check that seems silly but avoids having to handle bad data downtream, which is complicated by the fact that xctr functions do tolerate 0-row `co2`. This PR then leaves a test that clarifies that XSTR functions are different in this respect. 
REFACTORING
* Run the automatic styler (turns `1/3` into `1 / 3`).
* Remove duplication via `xstr_check()`
----
TODO
EXCEPTIONS
This PR is pretty simple. I'm OK without review.
=> XSTR functions now stop if  `scenarios` has 0-row

NEWS.md, R/utils-xstr.R, R/utils.R, R/xctr.R, R/xctr_at_product_level.R, inst/WORDLIST, man/xctr.Rd, tests/testthat/test-pstr.R, tests/testthat/test-xctr-inputs.R, tests/testthat/test-xctr.R, vignettes/articles/tiltIndicator.Rmd
Relates to #337 
This PR extends the idea of #337 to XCTR functions.
REFACTORING
I extract and modify a function that is now reused in all indicators.
----
TODO
EXCEPTIONS
=> XCTR functions now stop if `co2` has 0-row

R/istr.R, R/pstr.R, R/utils-xstr.R, R/xctr_at_product_level.R, tests/testthat/test-istr.R, tests/testthat/test-pstr.R, tests/testthat/test-xctr-inputs.R, tests/testthat/test-xctr.R
Same as #337 and #338 but for `companies` in all functions.
----
TODO
EXCEPTIONS
=> XXTR functions now stop if `companies` has 0-rows

tests/testthat/test-pstr.R, tests/testthat/test-xctr-inputs.R, tests/testthat/test-xctr.R
Relates to #176 
This PR simplifies, expands, and improves tests for the case when a company does or doesn't match `co2` or `scenarios` data. It's motivated by a bug I introduced in a PR where companies without matches didn't appear in the output when they were along with other companies with some match. 
----
TODO
EXCEPTIONS
=> Improve tests for cases with and without matches

R/pstr.R, R/utils.R, R/xctr_at_product_level.R
Closes #334 
This PR standardizes column names so that it's easier to reuse the code. It pushes renames to the boundaries of the code, i.e. either to the top or bottom of the process. A new family of internal `standardize*()` functions centralize the relevant code. You can look at it and quickly learn which names to expect in the core of the code. 
This allows us to more quickly adapt to changes in the input datasets. We show now need to only change code in the relevant `standardize*()` function.
Standard names ~ xctr (pstr):
* `companies_id` ~ `company_id`
* `grouped_by` ~ Benchmarks (`type`, `scenario`, `year`)
* `metric` ~ `co2_footprint` (`reductions`)
* `values_to_categorize` ~ Ranked `metric` (`metric`)
* `risk_category` ~ "high", "medium", "low"
----
TODO
EXCEPTIONS
This is purely …
=> New internal family to `standardize*()` column names

R/istr.R
Relates to #334 
This PR does with ISTR what #334 did with xctr and pstr, i.e. push renames to the boundaries so that the core of the code uses consistent column names.
----
TODO
EXCEPTIONS
Purely refactoring.
=> In ISTR push renames to the boundaries

R/istr.R, R/pstr.R, R/utils.R, R/xctr_at_product_level.R
Relates to #334 
This PR is purely refactoring, most notably, it remove the `metric` column I introduced in #334 because it resulted in complicated code.
----
TODO
EXCEPTIONS
This is refactoring. The existing tests are enough.
=> Refactor: Mainly remove `metric` in favour of `values_to_categorize`

R/istr.R, man/istr.Rd, tests/testthat/test-istr.R
Closes #332
Dear @kalashsinghal (cc @maurolepore),
Here is the PR that tackles the [ticket regarding the thresholds range](https://github.com/orgs/2DegreesInvesting/projects/13/views/10?pane=issue&itemId=28348053), that followed the PR that was doing the [same thing but for PSTR](https://github.com/2DegreesInvesting/tiltIndicator/pull/329).
I have 
- modified the main default arguments of the istr_at_product_level()
- written an unit test for istr() that checks the behavior (same one as test-pstr.R)
Thank you !! 
----
TODO
EXCEPTIONS
=> In ISTR default thresholds are now the same as in XCTR

R/istr.R, tests/testthat/test-istr.R
I have adapted easy tests from `test-pstr.R` file into the `test-istr.R` file. In the `test-istr.R` file, there are some TODOs which needs to be fixed which I will fix in another PR. This PR partially completes this [issue](https://github.com/2DegreesInvesting/tiltIndicator/issues/354). I will add more tests in different PRs depending on the complexity of tests. 
In this PR I have added tests without changing the logic of the ISTR code. Hence, I will merge this PR without a review as I haven't added a new logic or changed the existing code. Please review this merged PR after you come back from holidays! Thanks!  
----
TODO
EXCEPTIONS
=> Add easy tests from `test-pstr.R` file to remove common bugs in ISTR

R/istr.R, R/pstr.R
Relates to #364 
This PR does does a small and simple refactoring to remove a bit of duplication between ISTR and PSTR. It renames the first argument more generically as `data` (following the tidyverse design guide) so that it can mean both "companies" and "inputs". By doing so `istr_add_values_to_categorize()` becomes identical to `pstr_add_values_to_categorize()` so we can keep only one: `xstr_add_categories_to_categorize()`. 
----
TODO
EXCEPTIONS
FYI @kalashsinghal 
This is purely refactoring and the existing tests are enough. It's small and simple enough, and I believe this is what you intended when you wrote the TODO that this PR removes. It all seems straight forward so I may go ahead and merge without review.
=> Refactor: Remove duplication via `xstr_add_values_to_categorize()`

R/pstr_prepare_scenario.R, R/xstr_pivot_type_sector_subsector.R, R/xstr_polish_output_at_copmany_level.R, R/xstr_prune_companies.R, _pkgdown.yml, man/pstr_prepare_scenario.Rd, man/xstr_pivot_type_sector_subsector.Rd, man/xstr_polish_output_at_company_level.Rd, man/xstr_prune_companies.Rd
Relates to #373
This PR splits the family of helpers into those that are used before and after calculating tilt indicators.
----
TODO
EXCEPTIONS
Affects only the website.
=> Split helpers into pre- and post-processing helpers

R/utils-xstr.R
Relates to #419 
This PR extends `xstr_check()` to check crucial names in `scenarios`. Other PR(s) should follow to do the same with other datasets, both for XSTR and XCTR.
----
TODO
EXCEPTIONS
The existing tests are enough. We already check for graceful errors if those columns are missing. But the error was coming from a less related part of the code. The intent, however, was already covered by the tests so I don't need a reviewer.
=> `xstr_check()` now checks crucial names in `scenarios`

R/istr.R, R/pstr.R, R/utils.R, R/xctr_at_product_level.R
Relates to #422 
This PR does two refactorings:
* Adds thresholds to `data` to make it easier to later implement the logic to give year 2030 a different threshold.
* Renames `standardize*()` to `prepare*()` because it's  job is now more general.
----
TODO
EXCEPTIONS
This is pure refactoring and the existing tests are enough. For the same reason I don't need a review.
=> Refactor: Add thresholds to `.data`

R/istr.R, man/istr.Rd, tests/testthat/test-istr.R
This PR fixed a bug: It adds the arguments `low_threshold` and `high_threshold` to `istr()`. These arguments are available in `istr_at_product_level()` but there was no way to pass them to it from `istr()`.
----
TODO
EXCEPTIONS
This is a hotfix. The bug is clear and the solution simple.
=> `istr()` is now sensitive to `low_threshold` and `high_threshold`

vignettes/articles/tiltIndicator.Rmd
Closes #407.
Here is the PR where I have updated the Get started section of the tiltIndicator vignette to show that XSTR also exists in the main functions.
Thanks :) 
----
TODO
EXCEPTIONS
=> Update "Get started" section to reflect that XSTR now belongs to main functions

R/utils.R, tests/testthat/test-istr_at_product_level.R, tests/testthat/test-pstr_at_product_level.R, tests/testthat/test-xctr_at_product_level.R
Closes #435 
This PR fixes a bug that caused XSTR functions to error when `scenarios` had duplicated data.
----
TODO
EXCEPTIONS
=> XSTR no longer errors with duplicated scenarios

R/utils.R, man/istr.Rd, man/pstr.Rd, man/xctr.Rd, tests/testthat/_snaps/utils.md
Relates to #441 
This PR updates the value of the `xxtr()` functions to reflect the output includes results at both levels in nested columns `product` and `company`.
----
TODO
EXCEPTIONS
=> The helpfile of `xxtr()` now explain the nested columns `product` and `company`

DESCRIPTION, vignettes/articles/handling-long-runtime.Rmd
Closes #446 
This PR polishes the article "handling a long runtime" to help run the indicators with real data. The new features are defined in the article itself. I don't implement them in the package because their scope is beyond tiltIndicator -- they can help with any long-running process. But also there are already great dedicated tools for that, such as the awesome [targets](https://books.ropensci.org/targets/) package. So rather than re-inventing the wheel we should probably reuse the existing toolkit.
In fact, even the article is probabbly a bad idea because it uses a number of packages that tiltIndicator does not need. This means I have to describe those new dependencies in DESCRIPTION and import them during checks on GitHub. I may later revert these changes and move the article …
=> The article "Handling a long runtime" now shows an enhanced approach

R/xctr.R, tests/testthat/_snaps/xctr-inputs.md, tests/testthat/_snaps/xctr_at_company_level.md, tests/testthat/test-xctr_at_company_level.R
Closes #465 
Relates to 2degreesinvesting/tiltIndicatorAfter#16
This PR fixes a bug by which a company with no match would be lost if it's in a dataset with some other company with some match.
----
TODO
EXCEPTIONS
=> `xctr()` at company level now preserves companies that match nothing

R/xstr_pivot_type_sector_subsector.R, data-raw/istr_data.R, inst/extdata/pstr_companies.csv
closes #470 
@maurolepore These column changes are aimed to reduce extra lines of code in tiltIndicatorBefore and tiltIndicator packages. I did a similar change in tiltIndicatorBefore as well through this [PR](https://github.com/2DegreesInvesting/NLPTiltMatch/pull/46). Thanks for the review!
----
TODO
EXCEPTIONS
=> Change `weo` scenario column names to reduce common code in `tiltIndicatorBefore` and `tiltIndicator` packages

R/emissions_profile.R, R/emissions_profile_upstream.R, R/sector_profile.R, R/sector_profile_upstream.R, R/unnest.R, R/xstr_polish_output_at_copmany_level.R, README.Rmd, README.md, man/emissions_profile.Rd, man/emissions_profile_upstream.Rd, man/sector_profile.Rd, man/sector_profile_upstream.Rd, man/unnest_product.Rd, man/xstr_polish_output_at_company_level.Rd, vignettes/articles/handling-long-runtime.Rmd, vignettes/articles/tiltIndicator.Rmd
Relates to #477 
Relates to #490 
This PR uses helpers from tiltToyData rather than the brittle, explicit path to the files in that package. This is to avoid tiltIndicator "know too much" about implementation details of tiltToyData (e.g. the file format). 
----
TODO
EXCEPTIONS
=> Access files in tiltToyData via an interface

R/emissions_profile_any_at_product_level.R, R/sector_profile_any_prepare_scenario.R, R/sector_profile_at_product_level.R, R/sector_profile_upstream_at_product_level.R, R/spa.R, R/utils.R, tests/testthat/test-sector_profile_at_product_level.R, tests/testthat/test-sector_profile_upstream_at_product_level.R
Relates to #477 
Closes #499 
```
old_abbreviation new_abbreviation full_name                  
<chr>            <chr>            <chr>                      
1 PCTR             ep_              Emissions Profile          
2 ICTR             epu_             Emissions Profile Upstream
3 XCTR             epa_             Emissions Profile Any     
4 PSTR             sp_              Sector Profile             
5 ISTR             spu_             Sector Profile Upstream   
6 XSTR             spa_             Sector Profile Any  
```
----
TODO
EXCEPTIONS
=> Internal functions now use new abbreviations

.github/workflows/R-CMD-check_tilt-devel.yaml
Relates to #490. 
Now that some the datasets moved to tiltToyData, it's important to know quickly if any change there breaks the code here. This PR adds a workflow to check run R CMD check with the development version of tiltToyData. If that package changes in an incompatible way, this check should alert this package.
----
TODO
EXCEPTIONS
=> Check with devel version of other tilt packages

R/rowid.R, tests/testthat/_snaps/utils.md
Closes #515 
This issue clarifies that we don't pass `*rowid` columns to the output at company level.
----
TODO
EXCEPTIONS
=> Clarify why we don't pass `*rowid` columns to the output at company level

R/emissions_profile_any_add_values_to_categorize.R, man/emissions_profile_any_add_values_to_categorize.Rd, tests/testthat/test-emissions_profile_any_add_values_to_categorize.R
Relates to #599 
This PR completes #599:
* Documents all additional columns and rows.
* Tests that what the docs say is true.
* Tests that missing crucial columns yield an informative error message.
----
TODO
EXCEPTIONS
=> Improve docs and tests

R/any_at_company_level.R, R/emissions_profile_any_at_product_level.R, R/sector_profile_at_product_level.R, R/sector_profile_upstream_at_product_level.R, R/utils-cols.R, R/utils.R, tests/testthat/test-emissions_profile_any_at_product_level.R, tests/testthat/test-sector_profile_at_product_level.R, tests/testthat/test-sector_profile_upstream_at_product_level.R
Closes #587 
This PR modifies the output columns at product level so that `clustered` isn't `NA` when `risk_category` is `NA`.
This applies only at product level. The company level output lacks the columns `clustered`:
``` r
cols_at_company_level()
#> [1] "companies_id"  "grouped_by"    "risk_category" "value"
```
----
TODO
EXCEPTIONS
``` r
aka("uid")
#> [1] "activity_uuid_product_uuid"
companies <- example_companies(!!aka("uid") := NA)
products <- example_products()
emissions_profile(companies, products) |> unnest_product()
#> # A tibble: 1 × 6
#>   companies_id grouped_by risk_category clustered activity_uuid_product_uuid
#>   <chr>        <chr>      <chr>         <chr>     <chr> …
```
=> At product level when `risk_category` is `NA`, `clustered` isn't `NA`

R/example_data.R, tests/testthat/test-example_data.R
Surprisingly before they were a "character" but now they are a double.
``` r
typeof(example_products()$co2_footprint)
#> [1] "double"
typeof(example_inputs()$input_co2_footprint)
#> [1] "double"
```
<sup>Created on 2023-11-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
----
TODO
EXCEPTIONS
=> In `example_products()` and `*inputs()` `*co2_footprint` is now a double

R/emissions_profile_any_at_product_level.R, R/utils.R, tests/testthat/test-emissions_profile_any_at_product_level.R
Closes #629
This PR allows the column `*isic_4digit` to have any length. Maybe we should rename this column as it makes no sense that something called 4digit can have anything other than 4 digits. 
``` r
companies <- example_companies()
products <- example_products(!!aka("isic") := c(NA, "1", "12", "123", "12345"))
products
#> # A tibble: 5 × 5
#>   isic_4digit activity_uuid_product_uuid tilt_sector unit  co2_footprint
#>   <chr>       <chr>                      <chr>       <chr>         <dbl>
#> 1 <NA>        a                          a           a                 1
#> 2 1           a                          a           a                 1
#> 3 12          a                          a           a                 1
#> 4 123         a …
```
=> Allow `*isic*` values of any length

R/example_dictionary.R, tests/testthat/test-example_data.R
Relates to https://github.com/2DegreesInvesting/tiltIndicatorBefore/pull/69
This PR adds single quotes around values if `*isic*` columns in example datasets used in tests.
``` r
library(dplyr, warn.conflicts = FALSE)
example_inputs() |> relocate(matches("isic"))
#> # A tibble: 1 × 10
#>   input_isic_4digit activity_uuid_product_uuid input_activity_uuid_product_uuid
#>   <chr>             <chr>                      <chr>                           
#> 1 '1234'            a                          a                               
#> # ℹ 7 more variables: input_tilt_sector <chr>, input_tilt_subsector <chr>,
#> #   input_unit <chr>, input_co2_footprint <dbl>, type <chr>, sector <chr>,
#> #   subsector <chr>
example_products() |> …
```
=> Add single quotes around values of `*isic*` in example datasets

R/utils-test.R, tests/testthat/_snaps/emissions_profile.md, tests/testthat/_snaps/emissions_profile_upstream.md, tests/testthat/test-emissions_profile_upstream.R
Relates to https://github.com/2DegreesInvesting/tiltToyData/issues/23
This PR prepares tiltIndicator to update toy data. It simply updates snapshots before the new data is released and skips the snapshot tests unless the toy data is the new one.
I'll merge without review because it's clear that once the toy data is updated the snapshots need to be updated too.
----
TODO
EXCEPTIONS
=> Prepare for tiltToyData#23

.github/workflows/R-CMD-check-tiltPlot.yaml
Relates to https://github.com/2DegreesInvesting/tiltPlot/pull/79
This PR adds a GitHub-Actions workflow to run R CMD check on tiltPlot on each PR to tiltIndicator. This alerts potential breaking changes in tiltPlot from upstream dependencies.
This follows [Google's Beyoncé Rule](https://abseil.io/resources/swe-book/html/ch11.html)
> If you liked it, then you shoulda put a test on it.”
----
TODO
EXCEPTIONS
=> On every PR check tiltPlot on CI

R/rename.R, tests/testthat/test-emissions_profile.R, tests/testthat/test-sector_profile.R, tests/testthat/test-sector_profile_upstream.R
Relates to #719 
This PR adds a defunc error from the top level `xxtr()` functions -- which I had missed in #719.
----
TODO
EXCEPTIONS
=> The `xxtr()` functions now throw a defunc error

R/emissions_profile.R, R/epa_at_company_level.R, tests/testthat/test-emissions_profile.R, tests/testthat/test-emissions_profile_upstream.R
Merges into #639 
This PR adds into the same `value` the `NA`s due to missing benchmarks and the `NA`s due to unmatched products. This way we account for both types of `NA`s with the same 6-benchmarks we already have. 
reprex: https://bit.ly/tiltIndicator-729
@Tilmon I requested your review to touch base with you on my progress. But I'm still now ready to merge because I want to add more tests and refactoring. 
--
TODO (myself)
----
TODO
EXCEPTIONS
=> At company level perserve unmatched products via 6 benchmarks

tests/testthat/_snaps/emissions_profile.md, tests/testthat/test-emissions_profile.R
Closes #730 
The goal of this PR is to add an important test that was missing in the code base, and illustrate how a conceptual reprex translates into a test.
----
TODO
EXCEPTIONS
=> Test that the company-level output can actually have a non-zero `value`  in all levels of `risk_catrgory`

DESCRIPTION, NEWS.md, R/sector_profile.R, R/sector_profile_at_product_level.R, R/sector_profile_upstream.R, R/sector_profile_upstream_at_product_level.R, tests/testthat/_snaps/emissions_profile.md, tests/testthat/_snaps/emissions_profile_upstream.md, tests/testthat/test-sector_profile.R, tests/testthat/test-sector_profile_at_product_level.R, tests/testthat/test-sector_profile_upstream.R, tests/testthat/test-sector_profile_upstream_at_product_level.R
Closes #733 
Extends #639
> The "unmatched product" from the emission_profile is the equivalent to NOT having a tilt_sector and tilt_subsector  at all, because in that case, we won't be able to find any matching scenario and hence will only have NAs for that product.
-- Tilman [here](https://github.com/2DegreesInvesting/tiltIndicator/pull/738#issuecomment-1965169469)
--
@Tilmon and @AnneSchoenauer please see the reprexes and let me know if this is what you expect or what needs to change.
`sector_profile*()` now:
* preserves unmatched products at product level.
* adds the unmatched products to the `value` at company level.
<details/><summary/>reprex: `sector_profile()`</summary>
``` r
library(tibble)
options(tibble.print_max = Inf, width = …
```
=> The `sector*()` functions now preserve unmatched products

R/summarize_range.R, man/summarize_range.Rd, tests/testthat/test-summarize_range.R
* Relates to https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/188
----
``` r
data <- tibble::tibble(x = c(1, 2, 3, NA))
data |> summarize_range(x, na.rm = TRUE)
#> # A tibble: 1 × 2
#>     min   max
#>   <dbl> <dbl>
#> 1     1     3
data |> summarize_range(x)
#> # A tibble: 1 × 2
#>     min   max
#>   <dbl> <dbl>
#> 1    NA    NA
```
----
TODO
EXCEPTIONS
=> `summarize_range()` gains `na.rm` and defaults to removing `NA`s

R/summarize_range.R, man/summarize_range.Rd, tests/testthat/test-summarize_range.R
Relates to https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/188
This is the safer and most common default. The exclusion of missing values should be done explicitely by the users of the code (e.g. in tiltIndicatorAfter).
----
TODO
EXCEPTIONS
=> `summarize_range()` now defaults to `na.rm = FALSE`

R/summarize_range.R, tests/testthat/test-summarize_range.R
* Follows up on #764 
Here I remove a warning that now seems to cause more pain than good.
----
TODO
EXCEPTIONS
=> Remove a warning that seems more work than benefit

R/example_dictionary.R, tests/testthat/test-example_data.R
* Closes #801
* Relates to #799 (thanks @kalashsinghal)
This PR makes `example_products()` better reflect the corresponding dataset in tiltToyData.
-  [x] Mark the PR as draft.
=> `example_products()` gains `tilt_subsector`

.github/workflows/test-coverage.yaml, R/emissions_profile_any_at_product_level.R
Relates to https://github.com/2DegreesInvesting/TiltDevProjectMGMT/issues/234
This PR ensures that all products for a company are included in the final output at product level which don't have any result for emission profile.
Reprex:
``` r
library(readr)
library(dplyr)
library(tiltAddCO2)
library(tiltIndicatorAfter)
devtools::load_all(".")
options(width = 500)
profile_rank_sample <- profile_rank_sample()
profile_rank_sample
#> # A tibble: 6 × 6
#>   activity_uuid_product_uuid co2_footprint tilt_subsector unit  isic_4digit tilt_sector
#>   <chr>                              <dbl> <chr>          <chr> <chr>       <chr>      
#> 1 uuid_1                                 1 land use       kg    '2345'      sector     
#> 2 uuid_2                                 2 land …
```
=> Include all products for a company with no results for emission profile at product level
